### ISSUE TITLE
Cannot start the sample OPC Server.

### ISSUE THREAD

**Issue by x19chen** [Azure/azure-iiot-opc-twin-api#2]
Hello,

I was following the Wiki to test and learn the Azure IIoT OPC Suite.
I tried to start the sample OPC Server, using the command, `docker run -it marcschier/azure-iiot-opc-twin . --sample 51210`, it gave me the following error.
`Unknown .
Usage:       Microsoft.Azure.IIoT.OpcUa.Servers.Cli [options] operation [args]
Operations (Mutually exclusive):
    --sample <port>
             Run opc ua sample server instance
Options:
     -p
    --port
             Port to run the server on.  Can be specified multiple times.
    --help
     -?
     -h      Prints out this help.`
I tried another command, `docker run -it -p 51210:51210 marcschier/azure-iiot-opc-twin --sample`, the server was started. However, I was not sure if it was what you meant.
Please have a look on that.

Best Regards,
Xiaoyang

**Comment by marcschier** [comment]
Hi @x19chen.  I have updated wiki to reflect -p arg.  But without that argument it should be ok, too (51210 I believe is the default port).

**Comment by x19chen** [comment]
Sorry, but I think it does not solve the issue.
When I give the command,
`docker run -it marcschier/azure-iiot-opc-twin . --sample -p 51210`,
the error message states that
`Unknown .`.
This indicates that the dot after the image name is invalid.
I am not sure if the dot is a typo, I am using Docker for Windows.
In addition, I would say it would also be useful to expose the port via, for example, `-p 51210:51210`. Otherwise even if the server is started, one cannot access it from the outside of the docker container.
